// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourism_App.Data;

#nullable disable

namespace Tourism_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024150418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tourism_App.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("ChargePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId1")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[NumberOfPeople] * [ChargePerPerson]");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DestinationId1");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Tourism_App.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The City of Light, known for Eiffel Tower, Louvre Museum, and romantic ambiance. Explore the Seine River cruises, Montmartre's artistic charm, Notre-Dame Cathedral, and world-class cuisine including croissants and fine wines.",
                            ImageUrl = "https://images.unsplash.com/photo-1431274172761-fca41d930114?w=800&h=600&fit=crop",
                            Location = "France",
                            Name = "Paris, France",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A bustling metropolis blending traditional culture with cutting-edge technology. Visit Shibuya Crossing, ancient temples like Senso-ji, neon-lit districts, sushi restaurants, and experience bullet trains and futuristic skyscrapers.",
                            ImageUrl = "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop",
                            Location = "Japan",
                            Name = "Tokyo, Japan",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tropical paradise with beautiful beaches, temples, and vibrant culture. Relax on pristine beaches, hike volcanoes like Mount Batur, explore rice terraces in Ubud, and enjoy traditional Balinese dances and ceremonies.",
                            ImageUrl = "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800&h=600&fit=crop",
                            Location = "Indonesia",
                            Name = "Bali, Indonesia",
                            Price = 800m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ancient history meets modern charm in the Eternal City with Colosseum and Vatican. Wander through ancient Roman ruins, visit St. Peter's Basilica, toss coins in the Trevi Fountain, and savor authentic Italian pizza and gelato.",
                            ImageUrl = "https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800&h=600&fit=crop",
                            Location = "Italy",
                            Name = "Rome, Italy",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Luxury and innovation in the desert with Burj Khalifa and stunning architecture. Experience desert safaris, luxury shopping at Dubai Mall, indoor skiing at Ski Dubai, and breathtaking views from the world's tallest building.",
                            ImageUrl = "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop",
                            Location = "UAE",
                            Name = "Dubai, UAE",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Iconic Opera House and Harbour Bridge in a vibrant coastal city. Enjoy harbor cruises, relax at Bondi Beach, visit the Sydney Aquarium, and explore the Royal Botanic Gardens with stunning ocean views.",
                            ImageUrl = "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&h=600&fit=crop",
                            Location = "Australia",
                            Name = "Sydney, Australia",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Stunning sunsets and white-washed buildings overlooking the Aegean Sea. Discover blue-domed churches, volcanic beaches, ancient Minoan ruins, and enjoy local wines while watching spectacular Mediterranean sunsets.",
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&h=600&fit=crop",
                            Location = "Greece",
                            Name = "Santorini, Greece",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Overwater bungalows and crystal-clear waters in paradise islands. Dive into coral reefs, enjoy private beach dinners, relax in luxury spas, and experience world-class snorkeling in the Indian Ocean's clearest waters.",
                            ImageUrl = "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&h=600&fit=crop",
                            Location = "Maldives",
                            Name = "Maldives",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 9,
                            Description = "The iconic symbol of love, a magnificent white marble mausoleum built by Mughal Emperor Shah Jahan. Marvel at intricate Mughal architecture, reflective pools, and beautiful gardens, while learning about the legendary love story of Shah Jahan and Mumtaz Mahal.",
                            ImageUrl = "https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=800&h=600&fit=crop",
                            Location = "India",
                            Name = "Taj Mahal, Agra, India",
                            Price = 600m
                        },
                        new
                        {
                            Id = 10,
                            Description = "The Pink City with stunning palaces, forts, and vibrant culture. Visit Amber Fort and City Palace. Explore royal heritage, bustling markets, elephant rides to forts, and experience traditional Rajasthani cuisine and folk performances.",
                            ImageUrl = "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&h=600&fit=crop",
                            Location = "India",
                            Name = "Jaipur, Rajasthan, India",
                            Price = 500m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Beautiful beaches, Portuguese architecture, and vibrant nightlife. Perfect for relaxation and adventure. Relax on golden sands, explore colonial churches, enjoy water sports, and experience Goan cuisine with Portuguese influences.",
                            ImageUrl = "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop",
                            Location = "India",
                            Name = "Goa, India",
                            Price = 700m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Serene houseboat cruises through palm-fringed canals, lush greenery, and traditional village life. Experience traditional Kerala houseboats, spice plantations, wildlife sanctuaries, and authentic Ayurvedic treatments amidst tropical backwaters.",
                            ImageUrl = "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=600&fit=crop",
                            Location = "India",
                            Name = "Kerala Backwaters, India",
                            Price = 800m
                        },
                        new
                        {
                            Id = 13,
                            Description = "The spiritual capital of India with ancient temples, ghats along the Ganges, and rich cultural heritage. Witness sacred Ganges rituals, explore ancient temples, take boat rides at dawn, and immerse in India's oldest living city's spiritual traditions.",
                            ImageUrl = "https://images.unsplash.com/photo-1699630923504-9a24dbaab37c?w=800&h=600&fit=crop",
                            Location = "India",
                            Name = "Varanasi, India",
                            Price = 450m
                        },
                        new
                        {
                            Id = 14,
                            Description = "The city that never sleeps with Bollywood glamour, colonial architecture, and bustling street life. Visit the Gateway of India, explore Bollywood studios, enjoy street food, and experience the vibrant mix of cultures in India's financial capital.",
                            ImageUrl = "https://images.unsplash.com/photo-1562979314-bee7453e911c?w=800&h=600&fit=crop",
                            Location = "India",
                            Name = "Mumbai, India",
                            Price = 650m
                        });
                });

            modelBuilder.Entity("Tourism_App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@tourismapp.com",
                            FullName = "Administrator",
                            IsAdmin = true,
                            Password = "admin123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Tourism_App.Models.Booking", b =>
                {
                    b.HasOne("Tourism_App.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tourism_App.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId1");

                    b.HasOne("Tourism_App.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tourism_App.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Destination");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
